spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.100:8848

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.wzh.spring.cloud.alibaba.dubbo.provider.service
  registry:
    address: spring-cloud://192.168.1.100
  protocol:
    # dubbo 协议
    name: dubbo
      # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    serialization: kryo
  provider:
    loadbalance: roundrobin
port: 8080
